### ISSUE TITLE
Suggested new profile name

### ISSUE THREAD

**Issue by msmock** [IHE/ITI.SeR#10]
# Open Issues and Questions

11. As the profile covers not only document retrieval, shall it be renamed from
    "Secure Retrieve" (SeR) to e.g. "User Authorization" (UAZ)?

**Comment by msmock** [comment]
The name "User Authorization" and when abbreviated as UAZ sounds strange to me. 

I suggest to use the name "Access Decision Delegation" (ADD) which matches exactly what the profile defines: A framework for actors grouped with the Verifier to delegate access decisions to a single instance which implements the Authorization Decision Manager actor.

**Comment by unixoid** [comment]
Ideas:
* Health IT Access Decision Delegation (HADD)
