### ISSUE TITLE
Need source for the uml diagrams 

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.SeR#15]
Please create the .plantuml files for the UML diagrams. We need these for maintenance and future use. (sorry that this publication form does not automate the rendering). 

Put the .plantuml files into a images-source folder

See publications guidance
* https://github.com/IHE/publications/wiki/UML-(webSequence---PlantUML)

**Comment by JohnMoehrke** [comment]
Note that once the .plantuml file is in github, you could provide a link to that file from your narrative. Some readers do like the plantuml format as it aids them with further derivation such as at a projectathon.

**Comment by JohnMoehrke** [comment]
looks like @msmock PR do include the source.   Martin, can you rename these to .plantuml rather than just .pu? IHE has chosen to use the longer extension.

Do these cover all of the UML diagrams? Or are there still some without UML source?

**Comment by msmock** [comment]
Renamed the source of the sequence diagrams for UC 2 and the mHealth Use Case to .plantuml. 

There is no source for the UML diagram of UC1 which was taken from the initial SeR version.

**Comment by msmock** [comment]
Done. See pull request from branch WI 2022 #15.
