### ISSUE TITLE
Use of "Document" in response message semantics where "Resource" is more generic. 

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.SeR#22]
The response message semantics frequently uses the term "document" to refer to the artefact to which access is being permitted/denied. For example:

Permit: if a valid authorization decision exists allowing the disclosure of the requested document to the Requester Entity.
Deny: if no valid authorization decisions exist for the identified Document/Requester Entity, or if authorization decision does not allow disclosure of the Document to the Requester Entity.
Indeterminate: if the Authorization Decisions Manager cannot discover if authorization decisions are granted (e.g., internal Errors, or DB unreachable for network problems, ...).
NotApplicable: if access to the requested document is not managed by the Authorization Decisions Manager. If the Authorization Decisions Manager cannot determine if the Requester Entity can access the resource requested.

Should these instances be replaced with the more generic term "Resource"?

**Comment by msmock** [comment]
We used clinical data in the document. To be consistent, I will replace the term "document" to clinical data first. If the TC decides to prefer "resource" instead of clinical data, we can replace globally afterwards.

**Comment by msmock** [comment]
Fixed
