### ISSUE TITLE
How are non-XDS Document Resources identified?

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.SeR#23]
Section 3.79.4.1.2.1.1 defines how to populate the <Resource> element for XDS Documents. Since this work item makes the profile more generic, should additional guidance be given for how to populate the <Resource> element for other types of resources?

**Comment by unixoid** [comment]
This guidance belongs to definitions of particular query types.

**Comment by unixoid** [comment]
21-Jul-2022: Leave open.

**Comment by unixoid** [comment]
F2F 03-Oct-2022: Dmytro to explain in 3.79.4.1.2.1.

**Comment by unixoid** [comment]
F2F 07-Oct-2022: Change reviewed and accepted.
